leftnav:
- identifier: 7e3ff208-2612-37b4-59b5-8ed013fb5c38
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 6a2c6179-75cf-b179-f595-8cd47525533f
  name: Calendar and Readings
  url: /pages/calendar-and-readings
  weight: 20
- identifier: 72fdf95b-a0da-075f-1a94-7af51fd620c7
  name: Instructor Insights
  url: /pages/instructor-insights
  weight: 30
- identifier: a5bbe7e5-0f66-f74a-26fc-7b59875ac05a
  name: Assignments
  url: /pages/assignments
  weight: 40
- identifier: ef2d07cc-784d-b741-628c-f172efdebf78
  name: Related Resources
  url: /pages/related-resources/
  weight: 50
- identifier: 34496f6d-91da-80c7-7e89-1181e2d8a583
  name: General
  parent: ef2d07cc-784d-b741-628c-f172efdebf78
  url: /pages/related-resources/general
  weight: 60
- identifier: f4c237d9-993f-6438-aff7-e527f7a7d406
  name: Petro Contra Branco
  parent: ef2d07cc-784d-b741-628c-f172efdebf78
  url: /pages/related-resources/petro-contra-branco
  weight: 70
- identifier: 6dcf0caf-463f-b811-11df-b144d7c7ee71
  name: Dois Filhos de Francisco
  parent: ef2d07cc-784d-b741-628c-f172efdebf78
  url: /pages/related-resources/dois-filhos-de-francisco
  weight: 80
- identifier: bcceb6ad-58f0-a57e-7d8a-6dc832eeaf4f
  name: Samba
  parent: ef2d07cc-784d-b741-628c-f172efdebf78
  url: /pages/related-resources/samba
  weight: 90
- identifier: 32f9f637-934e-f29c-1121-ae75a2654f2b
  name: Fado e Morna
  parent: ef2d07cc-784d-b741-628c-f172efdebf78
  url: /pages/related-resources/fado-e-morna
  weight: 100
- identifier: 05761f90-e894-a09c-677b-a198197ab37b
  name: "Lixo Extraordin\xE1rio / Waste Land"
  parent: ef2d07cc-784d-b741-628c-f172efdebf78
  url: /pages/related-resources/lixo-extraordinario-waste-land
  weight: 110
- identifier: 20393b55-8df2-e171-2a3b-7863d124b704
  name: Central do Brasil / Central Station
  parent: ef2d07cc-784d-b741-628c-f172efdebf78
  url: /pages/related-resources/central-do-brasil-central-station
  weight: 120
